car/urls.py
from django.urls import path
from .views import CarCreateView

urlpatterns = [
    path('sell/', CarCreateView.as_view(), name='sell'),
]

core/urls.py
from django.urls import path
from .views import DashboardListView
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
    path('', DashboardListView.as_view(), name='dashboard'),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('thank-you/', TemplateView.as_view(template_name='thank_you.html'), name="thank-you")
]

dodgy_bros/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('core.urls', "core"), namespace="core")),
    path('', include(('car.urls', "car"), namespace="car")),
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car/models.py
from django.db import models
from core.models import TimeStampModel

# Create your models here.

class Car(TimeStampModel):
    CONDITION_TYPES = (
        ('poor', 'Poor'),
        ('fair', 'Fair'),
        ('good', 'Good'),
        ('excellent', 'Excellent'),
    )
    seller_name = models.CharField(max_length=255)
    seller_mobile = models.CharField(max_length=255)
    make = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    year = models.DateTimeField()
    condition = models.CharField(max_length=255, choices=CONDITION_TYPES, 
        default="good", db_index=True)
    price = models.PositiveIntegerField()
    is_sold = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.seller_name}"

core/models.py
from django.db import models

# Create your models here.

USER_TYPES = (
    ('seller', 'Seller'),
    ('buyer', 'Buyer'),
)

class TimeStampModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

car/forms.py
from django.forms import ModelForm
from .models import Car
from django.core.exceptions import ValidationError

class CarForm(ModelForm):
    class Meta:
        model = Car
        fields = '__all__'

    def clean(self):
        data = self.cleaned_data
        if data['price'] < 1000 or data['price'] > 100000:
            raise ValidationError('Price must be between 1000 to 100000!')

car/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from .forms import CarForm

# Create your views here.


class CarCreateView(FormView):
    template_name = 'car/car_create.html'
    form_class = CarForm
    # success_url = '/thank-you/'

    def form_valid(self, form):
        # This method is called when valid form data has been POST.
        obj = form.save()
        return render(self.request, 'thank_you.html', {"id":obj.id})

core/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from car.models import Car
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger

# Create your views here.

class DashboardListView(ListView):
    model = Car
    paginate_by = 10
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        objects = self.model.objects.all().order_by("-created")
        paginator = Paginator(objects, self.paginate_by)
        page = self.request.GET.get('page')
        try:
            car_list = paginator.page(page)
        except PageNotAnInteger:
            car_list = paginator.page(1)
        except EmptyPage:
            car_list = paginator.page(paginator.num_pages)
        context['object_list'] = car_list 
        return context

templates/base.html
{% load static %}

<!DOCTYPE HTML>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css">
    {% block title %}
      <title>Dodgy Bros site</title>
    {% endblock title %}
    {% block css %}{% endblock%}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="{% url 'core:dashboard' %}"><h2>DODGY <i style="color:red;">BROS</i> SITE</h2></a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        </ul>
        <div class="form-inline my-2 my-lg-0">
          {% if request.user.is_authenticated %}
            <h2 class="my-2 my-sm-0">{{ request.user.username|title }}</h2>&nbsp;&nbsp;
            <a class="btn btn-outline-danger my-2 my-sm-0" href="{% url 'core:logout' %}">Logout</a>
          {% else %}
            <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'core:login' %}">Login</a>
          {% endif %}
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}{% endblock%}
    </div>

    <script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
    <script type="text/javascript" src="http://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    {% block js %} {% endblock %}
  </body>
</html>

templates/car/car_create.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block css %}
{% endblock %}

{% block content %}
  <div class="row" style="float:center;">
    <h1>Sell your car</h1>
  </div>
  {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
  <form class="form-signin" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label>Seller Name</label>
      {{ form.seller_name|add_class:"form-control"|attr:"placeholder:Enter Seller Name" }}
    </div>
    <div class="form-group">
      <label>Seller Mobile</label>
      {{ form.seller_mobile|add_class:"form-control"|attr:"placeholder:Enter Seller Mobile" }}
    </div>
    <div class="form-group">
      <label>Make</label>
      {{ form.make|add_class:"form-control"|attr:"placeholder:Enter Make" }}
    </div>
    <div class="form-group">
      <label>Model</label>
      {{ form.model|add_class:"form-control"|attr:"placeholder:Enter Model" }}
    </div>
    <div class="form-group">
      <label>Year</label>
      {{ form.year|add_class:"form-control datetimepicker"|attr:"placeholder:Enter Year" }}
    </div>
    <div class="form-group">
      <label>Condition</label>
      {{ form.condition|add_class:"form-control" }}
    </div>
    <div class="form-group">
      <label>Price</label>
      {{ form.price|add_class:"form-control"|attr:"placeholder:Enter Car Price" }}
    </div>
    <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Submit</button>
    <hr class="my-4">
  </form>  
{% endblock %}

{% block js %}
  <script type="text/javascript">
    $(document).ready(function(){
      $('.datetimepicker').datetimepicker({
        format: "Y-m-d"
      });
    });
  </script>
{% endblock %}

templates/dashboard.html
{% extends 'base.html' %}

{% block css %}
{% endblock %}

{% block content %}
  <a class="btn btn-primary" href="{% url 'car:sell' %}">List Car</a><br/><br/>

  {% for object in object_list %}
    <div class="card">
      <div class="card-header">ID:- {{object.id}} <span class="float-right">Created:- {{object.created|date:"M d, Y" }}</span></div>
      <div class="card-body">
        <h5 class="card-title">{{ object.model }}</h5>
        <p class="card-text">
          Make:- {{ object.make }} <br>
          Year:- {{ object.year|date:"M d, Y"  }} <br>
          Condition:- {{ object.condition }} <br>
          Price:- {{ object.price }} <br>
        </p>
        {% if object.is_sold %}
          <button href="#" disabled class="btn btn-danger float-right">SOLD</button>
        {% else %}
          <a href="#" class="btn btn-primary float-right">Buy</a>
        {% endif %}
      </div>
    </div><br>
  {% endfor %}
  {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li>
          <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
        </li>
      {% endif %}
        <li class="">
          <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
        </li>
     {% if page_obj.has_next %}
        <li>
            <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
        </li>
      {% endif %}
    </ul>
  {% else %}
    <h3>Your File Exam</h3>
    <p>File not yet available</p>
  {% endif %}
{% endblock %}

{% block js %}
{% endblock %}

templates/thank_you.html
{% extends 'base.html' %}

{% block content %}
	<div class="jumbotron text-center">
	  <h1 class="display-3">Thank You!</h1>
	  <p class="lead"><strong>Listing id:- {{id}}</strong> We will get back to you soon</p>
	  <hr>
	  <p>
	    Having trouble? <a href="">Contact us</a>
	  </p>
	  <p class="lead">
	    <a class="btn btn-primary btn-sm" href="{% url 'core:dashboard' %}" role="button">Continue to homepage</a>
	  </p>
	</div>
{% endblock %}